<?php

namespace ContainerYCadg2l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BiYvjyiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.biYvjyi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.biYvjyi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'departmentRepository' => ['privates', 'App\\Repository\\DepartmentRepository', 'getDepartmentRepositoryService', true],
        ], [
            'departmentRepository' => 'App\\Repository\\DepartmentRepository',
        ]);
    }
}
