<?php

namespace ContainerYCadg2l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CfLHIZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._cfLHIZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._cfLHIZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'departmentRepository' => ['privates', 'App\\Repository\\DepartmentRepository', 'getDepartmentRepositoryService', true],
            'user' => ['privates', '.errored..service_locator._cfLHIZ.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator._cfLHIZ": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'departmentRepository' => 'App\\Repository\\DepartmentRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
