<?php

namespace ContainerX0umozS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EQ_DkTwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eQ.dkTw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eQ.dkTw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\UserController::create' => ['privates', '.service_locator.foVwPZq', 'get_ServiceLocator_FoVwPZqService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator._cfLHIZ', 'get_ServiceLocator_CfLHIZService', true],
            'App\\Controller\\UserController::formCreate' => ['privates', '.service_locator.biYvjyi', 'get_ServiceLocator_BiYvjyiService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.YV9CA6V', 'get_ServiceLocator_YV9CA6VService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.2Bu6u53', 'get_ServiceLocator_2Bu6u53Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\UserController:create' => ['privates', '.service_locator.foVwPZq', 'get_ServiceLocator_FoVwPZqService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.GkGK2OS', 'get_ServiceLocator_GkGK2OSService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator._cfLHIZ', 'get_ServiceLocator_CfLHIZService', true],
            'App\\Controller\\UserController:formCreate' => ['privates', '.service_locator.biYvjyi', 'get_ServiceLocator_BiYvjyiService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.YV9CA6V', 'get_ServiceLocator_YV9CA6VService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.2Bu6u53', 'get_ServiceLocator_2Bu6u53Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\UserController::create' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::formCreate' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\UserController:create' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:formCreate' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
